export const CHECK_LABELS: Record<string, string> = {
  // DNS
  spf: 'SPF Record',
  dmarc: 'DMARC Policy',
  dnssec: 'DNSSEC',
  caa: 'CAA Records',
  mx: 'MX Records',
  ns: 'Nameservers',
  ns_lame: 'Lame Delegation',
  ns_delegation: 'NS Delegation',
  dkim: 'DKIM',
  mta_sts: 'MTA-STS',
  tlsrpt: 'SMTP TLS Reporting',
  bimi: 'BIMI',
  cname_apex: 'CNAME at Apex',
  https_svcb: 'HTTPS Record',
  ttl: 'TTL Consistency',
  dnskey_algorithm: 'DNSKEY Algorithm',
  dnssec_rollover: 'DNSSEC Key Rollover',
  infrastructure: 'Infrastructure',
  // TLS
  chain_trusted: 'Chain of Trust',
  not_expired: 'Not Expired',
  hostname_match: 'Hostname Match',
  chain_complete: 'Chain Complete',
  strong_signature: 'Signature Algorithm',
  key_strength: 'Key Strength',
  expiry_window: 'Expiry Window',
  cert_lifetime: 'Certificate Lifetime',
  san_quality: 'SAN Quality',
  aia_reachability: 'AIA Reachability',
  tls_version: 'TLS Version',
  forward_secrecy: 'Forward Secrecy',
  aead_cipher: 'AEAD Cipher',
  ocsp_stapled: 'OCSP Stapling',
  ct_logged: 'CT Logged',
  caa_compliant: 'CAA Compliance',
  dane_valid: 'DANE / TLSA',
  consistency: 'Multi-IP Consistency',
  alpn_consistency: 'ALPN Consistency',
  ech_advertised: 'Encrypted Client Hello',
  hsts: 'HSTS',
  https_redirect: 'HTTPS Redirect',
  // IP
  reputation: 'IP Reputation',
};

export const CHECK_DESCRIPTIONS: Record<string, string> = {
  // DNS
  spf: 'SPF authorises which servers may send email for this domain',
  dmarc: 'DMARC instructs receivers how to handle unauthenticated messages',
  dnssec: 'DNSSEC cryptographically signs DNS records, preventing cache poisoning',
  caa: 'CAA restricts which Certificate Authorities may issue certificates',
  mx: 'MX records must agree between recursive and authoritative resolvers',
  ns: 'At least two NS records ensure availability if one nameserver fails',
  ns_lame: 'All NS records should respond authoritatively for the zone',
  ns_delegation: 'Parent and child NS records must be consistent',
  dkim: 'DKIM signs outgoing mail to prove it hasn\'t been tampered with',
  mta_sts: 'MTA-STS enforces TLS for inbound SMTP connections',
  tlsrpt: 'SMTP TLS Reporting provides visibility into delivery failures',
  bimi: 'BIMI displays a brand logo in supporting email clients',
  cname_apex: 'A CNAME at the zone apex breaks MX, NS and other records',
  https_svcb: 'HTTPS DNS records enable HTTP/3 and Encrypted Client Hello',
  ttl: 'Inconsistent TTLs across record types can cause caching problems',
  dnskey_algorithm: 'Deprecated DNSSEC algorithms (RSA/MD5, RSA/SHA-1) must be replaced',
  dnssec_rollover: 'DNSSEC key rollover must be clean — no orphaned DS or duplicate KSKs',
  infrastructure: 'Infrastructure checks: NS lame delegation and delegation consistency',
  // TLS
  chain_trusted: 'The certificate chain must verify to a trusted root CA',
  not_expired: 'All certificates in the chain must be within their validity period',
  hostname_match: 'The leaf certificate SAN must cover the queried hostname',
  chain_complete: 'All intermediate certificates must be present in correct order',
  strong_signature: 'SHA-1 and MD5 signatures are deprecated and must not appear in the chain',
  key_strength: 'RSA keys must be ≥ 2048 bits; ECDSA must use P-256 or better',
  expiry_window: 'Certificate expires within 30 days (warn) or 7 days (fail)',
  cert_lifetime: 'CA/Browser Forum requires certificates to be valid for ≤ 398 days',
  san_quality: 'The SAN list should be reasonable in size and not overly broad',
  aia_reachability: 'AIA CA Issuers URL must be reachable when the chain is incomplete',
  tls_version: 'TLS 1.3 is preferred; TLS 1.2 acceptable; older versions must not be offered',
  forward_secrecy: 'Ephemeral key exchange protects past sessions if the key is later compromised',
  aead_cipher: 'AEAD ciphers (GCM, ChaCha20-Poly1305) provide authenticated encryption',
  ocsp_stapled: 'OCSP stapling avoids a separate revocation check by the browser',
  ct_logged: 'Certificate Transparency requires ≥ 2 SCTs for browser trust',
  caa_compliant: 'The issuing CA must be authorised by the domain\'s CAA records',
  dane_valid: 'TLSA records must match the presented certificate if DANE is configured',
  consistency: 'All resolved IPs must present the same certificate and TLS configuration',
  alpn_consistency: 'ALPN protocol negotiation must be consistent across all IPs',
  ech_advertised: 'Encrypted Client Hello hides the hostname from passive observers',
  hsts: 'HTTP Strict Transport Security forces browsers to use HTTPS for ≥ 6 months',
  https_redirect: 'HTTP must redirect to HTTPS',
  // IP
  reputation: 'IP reputation: VPNs warn, Tor exit nodes and known C2 hosts fail',
};
