FROM scratch
COPY GeoLite2-ASN.mmdb GeoLite2-City.mmdb regexes.yaml tor_exit_nodes.txt /data/
COPY feodo_botnet_ips.txt vpn_ranges.txt cloud_provider_ranges.jsonl /data/
COPY datacenter_ranges.txt bot_ranges.jsonl spamhaus_drop.txt /data/
